name: Auto Generate versions.json

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate versions.json
        run: |
          echo "{" > versions.json

          first=true

          for file in Fungsi.lua.txt Fungsi2.lua.txt Fungsi3.lua.txt Gui.lua.txt Gui2.lua.txt
          do
            if [ -f "$file" ]; then
              name=$(echo "$file" | sed 's/.txt$//')
              hash=$(sha1sum "$file" | awk '{print $1}')
              len=$(wc -c < "$file" | tr -d ' ')

              if [ "$first" = true ]; then
                first=false
              else
                echo "," >> versions.json
              fi

              echo -n "\"$name\": {\"hash\": \"$hash\", \"len\": $len}" >> versions.json
            fi
          done

          echo "" >> versions.json
          echo "}" >> versions.json

      - name: Commit changes
        run: |
          git config user.name "auto-bot"
          git config user.email "bot@example.com"

          git add versions.json
          git diff --cached --quiet || git commit -m "auto update versions.json"

      - name: Push changes
        run: |
          git push
